default:
  image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  resource_group: webex-workspaces
  variables:
    GIT_REMOTE_URL: ssh://dokku@dokku.na.akqa.net:22/webex-workspaces-$CI_COMMIT_BRANCH
  script: 
    - dokku-deploy
  after_script: 
    - dokku-unlock
